version: '3.7'
services:
  webjenkins:
    container_name: jenkins
    image: 'jenkins/jenkins:lts'
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./data:/var/jenkins_home
    network_mode: "bridge"